name: Lint Codebase
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
      - feature/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint-codebase:
    name: Lint Codebase
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # Checkout repository Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      # Lint python codebase with flake8
      - name: Lint with flake8
        run: |
          flake8 --count --show-source --statistics

      # Lint yaml pipelines with yamllint
      - name: Lint with yamllint
        run: |
          yamllint -c .yamllint.yml .
