name: Build & Publish Container

on: [push]
jobs:
  Publish-Container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: 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
      - name: Build the hello-docker Docker image
        run: |
              docker build . --tag ghcr.io/powellrhys/strava-api:latest
              docker push ghcr.io/powellrhys/strava-api:latest